### ISSUE TITLE
Issues with king move calculation?

### ISSUE THREAD

**Issue by lemonjuiceexe** [lemonjuiceexe/Chess#19]
![image](https://user-images.githubusercontent.com/74901431/104644306-e2d6f000-56ad-11eb-9f8c-265a50154aa1.png)
In this position, for example, white king should be able to take a rook - and it's not. Issue needs further investigation.

**Comment by Bruhtek** [comment]
Have you tried clicking the rook, or other pieces that may protect it? I found it working when i did that

**Comment by lemonjuiceexe** [comment]
![image](https://user-images.githubusercontent.com/74901431/106480603-db845480-64ab-11eb-8183-ccbfb779e4b6.png)
Again; Kxb5 should be possible here, and it's not
