### ISSUE TITLE
Locked king

### ISSUE THREAD

**Issue by lemonjuiceexe** [lemonjuiceexe/Chess#21]
If you try to take a piece you can't (a protected piece with a king) you can't select the king afterwards (forever).

**Comment by lemonjuiceexe** [comment]
The piece you try to take becomes the selected piece according to the board, even though it's other color than the color on move.

**Comment by Bruhtek** [comment]
> 
> 
> The piece you try to take becomes the selected piece according to the board, even though it's other color than the color on move.

That is currently intended, you can still select other color pieces, you just can't move them, apart from that, king should be select-able now
