### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by Bruhtek** [lemonjuiceexe/Chess#25]
When the king is under a check, and you click on the checking figure, the following error emerges:
![image](https://user-images.githubusercontent.com/41647874/121917736-b1824f00-cd35-11eb-8a5c-b773405d217f.png)
Example situation:
![image](https://user-images.githubusercontent.com/41647874/121917772-b8a95d00-cd35-11eb-8934-ee1a91757aba.png)
When you click on the black queen, the error emerges
This needs to be fixed before #24 can be merged

**Comment by Bruhtek** [comment]
This is probably due to the fact, that IsChecked also calculates the clicked figure at that position?

**Comment by lemonjuiceexe** [comment]
Actually, the error shows up if you click ANY of the pieces that is not on move while there's a check.
